export const worldCapitals = [
        {uniqueKey: 1,	front: 'Afghanistan',	back: 'Kabul',	disabled: false},
        {uniqueKey: 2,	front: 'Albania',	back: 'Tirana (Tirane)',	disabled: false},
        {uniqueKey: 3,	front: 'Algeria',	back: 'Algiers',	disabled: false},
        {uniqueKey: 4,	front: 'Andorra',	back: 'Andorra la Vella',	disabled: false},
        {uniqueKey: 5,	front: 'Angola',	back: 'Luanda',	disabled: false},
        {uniqueKey: 6,	front: 'Antigua and Barbuda',	back: "Saint John's",	disabled: false},
        {uniqueKey: 7,	front: 'Argentina',	back: 'Buenos Aires',	disabled: false},
        {uniqueKey: 8,	front: 'Armenia',	back: 'Yerevan',	disabled: false},
        {uniqueKey: 9,	front: 'Australia',	back: 'Canberra',	disabled: false},
        {uniqueKey: 10,	front: 'Austria',	back: 'Vienna',	disabled: false},
        {uniqueKey: 11,	front: 'Azerbaijan',	back: 'Baku',	disabled: false},
        {uniqueKey: 12,	front: 'Bahamas',	back: 'Nassau',	disabled: false},
        {uniqueKey: 13,	front: 'Bahrain',	back: 'Manama',	disabled: false},
        {uniqueKey: 14,	front: 'Bangladesh',	back: 'Dhaka',	disabled: false},
        {uniqueKey: 15,	front: 'Barbados',	back: 'Bridgetown',	disabled: false},
        {uniqueKey: 16,	front: 'Belarus',	back: 'Minsk',	disabled: false},
        {uniqueKey: 17,	front: 'Belgium',	back: 'Brussels',	disabled: false},
        {uniqueKey: 18,	front: 'Belize',	back: 'Belmopan',	disabled: false},
        {uniqueKey: 19,	front: 'Benin',	back: 'Porto Novo',	disabled: false},
        {uniqueKey: 20,	front: 'Bhutan',	back: 'Thimphu',	disabled: false},
        {uniqueKey: 21,	front: 'Bolivia',	back: 'La Paz (administrative), Sucre (official)',	disabled: false},
        {uniqueKey: 22,	front: 'Bosnia and Herzegovina',	back: 'Sarajevo',	disabled: false},
        {uniqueKey: 23,	front: 'Botswana',	back: 'Gaborone',	disabled: false},
        {uniqueKey: 24,	front: 'Brazil',	back: 'Brasilia',	disabled: false},
        {uniqueKey: 25,	front: 'Brunei',	back: 'Bandar Seri Begawan',	disabled: false},
        {uniqueKey: 26,	front: 'Bulgaria',	back: 'Sofia',	disabled: false},
        {uniqueKey: 27,	front: 'Burkina Faso',	back: 'Ouagadougou',	disabled: false},
        {uniqueKey: 28,	front: 'Burundi',	back: 'Gitega',	disabled: false},
        {uniqueKey: 29,	front: 'Cambodia',	back: 'Phnom Penh',	disabled: false},
        {uniqueKey: 30,	front: 'Cameroon',	back: 'Yaounde',	disabled: false},
        {uniqueKey: 31,	front: 'Canada',	back: 'Ottawa',	disabled: false},
        {uniqueKey: 32,	front: 'Cape Verde',	back: 'Praia',	disabled: false},
        {uniqueKey: 33,	front: 'Central African Republic',	back: 'Bangui',	disabled: false},
        {uniqueKey: 34,	front: 'Chad',	back: "N'Djamena",	disabled: false},
        {uniqueKey: 35,	front: 'Chile',	back: 'Santiago',	disabled: false},
        {uniqueKey: 36,	front: 'China',	back: 'Beijing',	disabled: false},
        {uniqueKey: 37,	front: 'Colombia',	back: 'Bogota',	disabled: false},
        {uniqueKey: 38,	front: 'Comoros',	back: 'Moroni',	disabled: false},
        {uniqueKey: 39,	front: 'Congo, Democratic Republic of the',	back: 'Kinshasa',	disabled: false},
        {uniqueKey: 40,	front: 'Congo, Republic of the',	back: 'Brazzaville',	disabled: false},
        {uniqueKey: 41,	front: 'Costa Rica',	back: 'San Jose',	disabled: false},
        {uniqueKey: 42,	front: "Côte d'Ivoire (Ivory Coast)",	back: 'Yamoussoukro',	disabled: false},
        {uniqueKey: 43,	front: 'Croatia',	back: 'Zagreb',	disabled: false},
        {uniqueKey: 44,	front: 'Cuba',	back: 'Havana',	disabled: false},
        {uniqueKey: 45,	front: 'Cyprus',	back: 'Nicosia',	disabled: false},
        {uniqueKey: 46,	front: 'Czech Republic (Czechia)[5]',	back: 'Prague',	disabled: false},
        {uniqueKey: 47,	front: 'Denmark',	back: 'Copenhagen',	disabled: false},
        {uniqueKey: 48,	front: 'Djibouti',	back: 'Djibouti',	disabled: false},
        {uniqueKey: 49,	front: 'Dominica',	back: 'Roseau',	disabled: false},
        {uniqueKey: 50,	front: 'Dominican Republic',	back: 'Santo Domingo',	disabled: false},
        {uniqueKey: 51,	front: 'East Timor',	back: 'Dili',	disabled: false},
        {uniqueKey: 52,	front: 'Ecuador',	back: 'Quito',	disabled: false},
        {uniqueKey: 53,	front: 'Egypt',	back: 'Cairo',	disabled: false},
        {uniqueKey: 54,	front: 'El Salvador',	back: 'San Salvador',	disabled: false},
        {uniqueKey: 55,	front: 'England',	back: 'London',	disabled: false},
        {uniqueKey: 56,	front: 'Equatorial Guinea',	back: 'Malabo',	disabled: false},
        {uniqueKey: 57,	front: 'Eritrea',	back: 'Asmara',	disabled: false},
        {uniqueKey: 58,	front: 'Estonia',	back: 'Tallinn',	disabled: false},
        {uniqueKey: 59,	front: 'Eswatini (Swaziland)',	back: 'Mbabana',	disabled: false},
        {uniqueKey: 60,	front: 'Ethiopia',	back: 'Addis Ababa',	disabled: false},
        {uniqueKey: 61,	front: 'Federated States of Micronesia',	back: 'Palikir',	disabled: false},
        {uniqueKey: 62,	front: 'Fiji',	back: 'Suva',	disabled: false},
        {uniqueKey: 63,	front: 'Finland',	back: 'Helsinki',	disabled: false},
        {uniqueKey: 64,	front: 'France',	back: 'Paris',	disabled: false},
        {uniqueKey: 65,	front: 'Gabon',	back: 'Libreville',	disabled: false},
        {uniqueKey: 66,	front: 'Gambia',	back: 'Banjul',	disabled: false},
        {uniqueKey: 67,	front: 'Georgia',	back: 'Tbilisi',	disabled: false},
        {uniqueKey: 68,	front: 'Germany',	back: 'Berlin',	disabled: false},
        {uniqueKey: 69,	front: 'Ghana',	back: 'Accra',	disabled: false},
        {uniqueKey: 70,	front: 'Greece',	back: 'Athens',	disabled: false},
        {uniqueKey: 71,	front: 'Grenada',	back: "Saint George's",	disabled: false},
        {uniqueKey: 72,	front: 'Guatemala',	back: 'Guatemala City',	disabled: false},
        {uniqueKey: 73,	front: 'Guinea',	back: 'Conakry',	disabled: false},
        {uniqueKey: 74,	front: 'Guinea-Bissau',	back: 'Bissau',	disabled: false},
        {uniqueKey: 75,	front: 'Guyana',	back: 'Georgetown',	disabled: false},
        {uniqueKey: 76,	front: 'Haiti',	back: 'Port au Prince',	disabled: false},
        {uniqueKey: 77,	front: 'Honduras',	back: 'Tegucigalpa',	disabled: false},
        {uniqueKey: 78,	front: 'Hungary',	back: 'Budapest',	disabled: false},
        {uniqueKey: 79,	front: 'Iceland',	back: 'Reykjavik',	disabled: false},
        {uniqueKey: 80,	front: 'India',	back: 'New Delhi',	disabled: false},
        {uniqueKey: 81,	front: 'Indonesia',	back: 'Jakarta',	disabled: false},
        {uniqueKey: 82,	front: 'Iran',	back: 'Tehran',	disabled: false},
        {uniqueKey: 83,	front: 'Iraq',	back: 'Baghdad',	disabled: false},
        {uniqueKey: 84,	front: 'Ireland',	back: 'Dublin',	disabled: false},
        {uniqueKey: 85,	front: 'Israel',	back: 'Jerusalem (very limited international recognition)',	disabled: false},
        {uniqueKey: 86,	front: 'Italy',	back: 'Rome',	disabled: false},
        {uniqueKey: 87,	front: 'Jamaica',	back: 'Kingston',	disabled: false},
        {uniqueKey: 88,	front: 'Japan',	back: 'Tokyo',	disabled: false},
        {uniqueKey: 89,	front: 'Jordan',	back: 'Amman',	disabled: false},
        {uniqueKey: 90,	front: 'Kazakhstan',	back: 'Nur-Sultan',	disabled: false},
        {uniqueKey: 91,	front: 'Kenya',	back: 'Nairobi',	disabled: false},
        {uniqueKey: 92,	front: 'Kiribati',	back: 'Tarawa Atoll',	disabled: false},
        {uniqueKey: 93,	front: 'Kosovo',	back: 'Pristina',	disabled: false},
        {uniqueKey: 94,	front: 'Kuwait',	back: 'Kuwait City',	disabled: false},
        {uniqueKey: 95,	front: 'Kyrgyzstan',	back: 'Bishkek',	disabled: false},
        {uniqueKey: 96,	front: 'Laos',	back: 'Vientiane',	disabled: false},
        {uniqueKey: 97,	front: 'Latvia',	back: 'Riga',	disabled: false},
        {uniqueKey: 98,	front: 'Lebanon',	back: 'Beirut',	disabled: false},
        {uniqueKey: 99,	front: 'Lesotho',	back: 'Maseru',	disabled: false},
        {uniqueKey: 100, front: 'Liberia',	back: 'Monrovia',	disabled: false},
        {uniqueKey: 101, front: 'Libya',	back: 'Tripoli',	disabled: false},
        {uniqueKey: 102, front: 'Liechtenstein',	back: 'Vaduz',	disabled: false},
        {uniqueKey: 103, front: 'Lithuania',	back: 'Vilnius',	disabled: false},
        {uniqueKey: 104, front: 'Luxembourg',	back: 'Luxembourg',	disabled: false},
        {uniqueKey: 105, front: 'Madagascar',	back: 'Antananarivo',	disabled: false},
        {uniqueKey: 106, front: 'Malawi',	back: 'Lilongwe',	disabled: false},
        {uniqueKey: 107, front: 'Malaysia',	back: 'Kuala Lumpur',	disabled: false},
        {uniqueKey: 108, front: 'Maldives',	back: 'Male',	disabled: false},
        {uniqueKey: 109, front: 'Mali',	back: 'Bamako',	disabled: false},
        {uniqueKey: 110, front: 'Malta',	back: 'Valletta',	disabled: false},
        {uniqueKey: 111, front: 'Marshall Islands',	back: 'Majuro',	disabled: false},
        {uniqueKey: 112, front: 'Mauritania',	back: 'Nouakchott',	disabled: false},
        {uniqueKey: 113, front: 'Mauritius',	back: 'Port Louis',	disabled: false},
        {uniqueKey: 114, front: 'Mexico',	back: 'Mexico City',	disabled: false},
        {uniqueKey: 115, front: 'Moldova',	back: 'Chisinau',	disabled: false},
        {uniqueKey: 116, front: 'Monaco',	back: 'Monaco',	disabled: false},
        {uniqueKey: 117, front: 'Mongolia',	back: 'Ulaanbaatar',	disabled: false},
        {uniqueKey: 118, front: 'Montenegro',	back: 'Podgorica',	disabled: false},
        {uniqueKey: 119, front: 'Morocco',	back: 'Rabat',	disabled: false},
        {uniqueKey: 120, front: 'Mozambique',	back: 'Maputo',	disabled: false},
        {uniqueKey: 121, front: 'Myanmar (Burma)',	back: 'Nay Pyi Taw',	disabled: false},
        {uniqueKey: 122, front: 'Namibia',	back: 'Windhoek',	disabled: false},
        {uniqueKey: 123, front: 'Nauru',	back: 'No official capital',	disabled: false},
        {uniqueKey: 124, front: 'Nepal',	back: 'Kathmandu',	disabled: false},
        {uniqueKey: 125, front: 'Netherlands',	back: 'Amsterdam',	disabled: false},
        {uniqueKey: 126, front: 'New Zealand',	back: 'Wellington',	disabled: false},
        {uniqueKey: 127, front: 'Nicaragua',	back: 'Managua',	disabled: false},
        {uniqueKey: 128, front: 'Niger',	back: 'Niamey',	disabled: false},
        {uniqueKey: 129, front: 'Nigeria',	back: 'Abuja',	disabled: false},
        {uniqueKey: 130, front: 'North Korea',	back: 'Pyongyang',	disabled: false},
        {uniqueKey: 131, front: 'North Macedonia (Macedonia)',	back: 'Skopje',	disabled: false},
        {uniqueKey: 132, front: 'Northern Ireland',	back: 'Belfast',	disabled: false},
        {uniqueKey: 133, front: 'Norway',	back: 'Oslo',	disabled: false},
        {uniqueKey: 134, front: 'Oman',	back: 'Muscat',	disabled: false},
        {uniqueKey: 135, front: 'Pakistan',	back: 'Islamabad',	disabled: false},
        {uniqueKey: 136, front: 'Palau',	back: 'Melekeok',	disabled: false},
        {uniqueKey: 137, front: 'Panama',	back: 'Panama City',	disabled: false},
        {uniqueKey: 138, front: 'Papua New Guinea',	back: 'Port Moresby',	disabled: false},
        {uniqueKey: 139, front: 'Paraguay',	back: 'Asuncion',	disabled: false},
        {uniqueKey: 140, front: 'Peru',	back: 'Lima',	disabled: false},
        {uniqueKey: 141, front: 'Philippines',	back: 'Manila',	disabled: false},
        {uniqueKey: 142, front: 'Poland',	back: 'Warsaw',	disabled: false},
        {uniqueKey: 143, front: 'Portugal',	back: 'Lisbon',	disabled: false},
        {uniqueKey: 144, front: 'Qatar',	back: 'Doha',	disabled: false},
        {uniqueKey: 145, front: 'Romania',	back: 'Bucharest',	disabled: false},
        {uniqueKey: 146, front: 'Russia',	back: 'Moscow',	disabled: false},
        {uniqueKey: 147, front: 'Rwanda',	back: 'Kigali',	disabled: false},
        {uniqueKey: 148, front: 'Saint Kitts and Nevis',	back: 'Basseterre',	disabled: false},
        {uniqueKey: 149, front: 'Saint Lucia',	back: 'Castries',	disabled: false},
        {uniqueKey: 150, front: 'Saint Vincent and the Grenadines',	back: 'Kingstown',	disabled: false},
        {uniqueKey: 151, front: 'Samoa',	back: 'Apia',	disabled: false},
        {uniqueKey: 152, front: 'San Marino',	back: 'San Marino',	disabled: false},
        {uniqueKey: 153, front: 'Sao Tome and Principe',	back: 'Sao Tome',	disabled: false},
        {uniqueKey: 154, front: 'Saudi Arabia',	back: 'Riyadh',	disabled: false},
        {uniqueKey: 155, front: 'Scotland',	back: 'Edinburgh',	disabled: false},
        {uniqueKey: 156, front: 'Senegal',	back: 'Dakar',	disabled: false},
        {uniqueKey: 157, front: 'Serbia',	back: 'Belgrade',	disabled: false},
        {uniqueKey: 158, front: 'Seychelles',	back: 'Victoria',	disabled: false},
        {uniqueKey: 159, front: 'Sierra Leone',	back: 'Freetown',	disabled: false},
        {uniqueKey: 160, front: 'Singapore',	back: 'Singapore',	disabled: false},
        {uniqueKey: 161, front: 'Slovakia',	back: 'Bratislava',	disabled: false},
        {uniqueKey: 162, front: 'Slovenia',	back: 'Ljubljana',	disabled: false},
        {uniqueKey: 163, front: 'Solomon Islands',	back: 'Honiara',	disabled: false},
        {uniqueKey: 164, front: 'Somalia',	back: 'Mogadishu',	disabled: false},
        {uniqueKey: 165, front: 'South Africa',	back: 'Pretoria, Bloemfontein, Cape Town',	disabled: false},
        {uniqueKey: 166, front: 'South Korea',	back: 'Seoul',	disabled: false},
        {uniqueKey: 167, front: 'South Sudan',	back: 'Juba',	disabled: false},
        {uniqueKey: 168, front: 'Spain',	back: 'Madrid',	disabled: false},
        {uniqueKey: 169, front: 'Sri Lanka',	back: 'Colombo',	disabled: false},
        {uniqueKey: 170, front: 'Sudan',	back: 'Khartoum',	disabled: false},
        {uniqueKey: 171, front: 'Suriname',	back: 'Paramaribo',	disabled: false},
        {uniqueKey: 172, front: 'Sweden',	back: 'Stockholm',	disabled: false},
        {uniqueKey: 173, front: 'Switzerland',	back: 'Bern',	disabled: false},
        {uniqueKey: 174, front: 'Syria',	back: 'Damascus',	disabled: false},
        {uniqueKey: 175, front: 'Taiwan',	back: 'Taipei',	disabled: false},
        {uniqueKey: 176, front: 'Tajikistan',	back: 'Dushanbe',	disabled: false},
        {uniqueKey: 177, front: 'Tanzania',	back: 'Dodoma',	disabled: false},
        {uniqueKey: 178, front: 'Thailand',	back: 'Bangkok',	disabled: false},
        {uniqueKey: 179, front: 'Togo',	back: 'Lome',	disabled: false},
        {uniqueKey: 180, front: 'Tonga',	back: "Nuku'alofa",	disabled: false},
        {uniqueKey: 181, front: 'Trinidad and Tobago',	back: 'Port of Spain',	disabled: false},
        {uniqueKey: 182, front: 'Tunisia',	back: 'Tunis',	disabled: false},
        {uniqueKey: 183, front: 'Turkey',	back: 'Ankara',	disabled: false},
        {uniqueKey: 184, front: 'Turkmenistan',	back: 'Ashgabat',	disabled: false},
        {uniqueKey: 185, front: 'Tuvalu',	back: 'Funafuti',	disabled: false},
        {uniqueKey: 186, front: 'Uganda',	back: 'Kampala',	disabled: false},
        {uniqueKey: 187, front: 'Ukraine',	back: 'Kiev',	disabled: false},
        {uniqueKey: 188, front: 'United Arab Emirates',	back: 'Abu Dhabi',	disabled: false},
        {uniqueKey: 189, front: 'United Kingdom',	back: 'London',	disabled: false},
        {uniqueKey: 190, front: 'United States',	back: 'Washington D.C.',	disabled: false},
        {uniqueKey: 191, front: 'Uruguay',	back: 'Montevideo',	disabled: false},
        {uniqueKey: 192, front: 'Uzbekistan',	back: 'Tashkent',	disabled: false},
        {uniqueKey: 193, front: 'Vanuatu',	back: 'Port Vila',	disabled: false},
        {uniqueKey: 194, front: 'Vatican City',	back: 'Vatican City',	disabled: false},
        {uniqueKey: 195, front: 'Venezuela',	back: 'Caracas',	disabled: false},
        {uniqueKey: 196, front: 'Vietnam',	back: 'Hanoi',	disabled: false},
        {uniqueKey: 197, front: 'Wales',	back: 'Cardiff',	disabled: false},
        {uniqueKey: 198, front: 'Yemen',	back: "Sana'a",	disabled: false},
        {uniqueKey: 199, front: 'Zambia',	back: 'Lusaka',	disabled: false},
        {uniqueKey: 200, front: 'Zimbabwe',	back: 'Harare',	disabled: false}
    ];